[build]
# overridden at build time; this is just to get some useful rust-analyzer help while developing
target = "../rust-targets/x86_64-anillo-ferro-macho.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
