image: registry.git.facekapow.dev/anillo-os/anillo-os:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-x86_64:
  stage: build
  script:
    - |
      mkdir -p build/x86_64
      cmake -S . -B build/x86_64 -G Ninja -DCMAKE_BUILD_TYPE=Release
      cmake --build build/x86_64
  artifacts:
    paths:
      - build/x86_64/disk.img
