[package]
name = "ferro"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
intrusive-collections = { version = "0.9.5", default-features = false, features = ["nightly"] }
static_assertions = "1.1.0"
