[tasks.build-one]
command = "cargo"
toolchain = "nightly"
args = ["build", "--target", "../rust-targets/${ANILLO_ARCH}-anillo-ferro-macho.json"]
dependencies = ["process-font"]

[tasks.test-one]
command = "cargo"
toolchain = "nightly"
args = ["test", "--target", "../rust-targets/${ANILLO_ARCH}-anillo-ferro-macho.json"]

[tasks.ramdisk-one]
command = "true"

[tasks.process-font]
command = "./scripts/process-font.py"
args = [
	"./resources/ter-u16n.psf",
	"${BUILD_DIR}/font"
]
